name: 'Pynt Newman GitHub Action'
description: 'Pynt API Security Tests'
author: 'Pynt.io'
branding:
  icon: 'check-circle'
  color: 'blue'
inputs:
  base-path:
    description: 'Path for Postman collection/environment files.'
    required: true
    default: './'
  postman-collection-filename:
    description: 'Postman collection file name (should exist under "base-path").'
    required: true
    default: 'collection.postman_collection.json'
  postman-environment-filename:
    description: 'Postman environment file name (should exist under "base-path").'
    required: false
    default: 'environment.postman_environment.json'
outputs:
  api-security-test-results:
    description: "placeholder"
    value: 0
runs:
  using: "composite"
  steps:
    - id: run_latest_pynt
      shell: bash
      run: |
        docker pull ghcr.io/pynt-io/pynt:latest
        docker run -v "${{ inputs.base-path }}":/etc/pynt/ --env-file "${{ toJson(github) }}" --rm --network="host"  ghcr.io/pynt-io/pynt:latest -c "${{ inputs.postman-collection-filename }}" -e "${{ inputs.postman-environment-filename }}" -r --no-upload-logs

